/**
 * Material Design icons.
 */
export enum IconMat {
  Add = 'add',
  AddCircle = 'add_circle',
  Apps = 'apps',
  ArrowDown = 'arrow_downward',
  Calendar = 'perm_contact_calendar',
  CaretDown = 'keyboard_arrow_down',
  CaretUp = 'keyboard_arrow_up',
  Check = 'check',
  CheckCircle = 'check_circle',
  CheckOutline = 'check_circle_outline',
  Dashboard = 'dashboard',
  Delete = 'delete',
  Edit = 'edit',
  Error = 'error',
  Email = 'email',
  Favorite = 'star_border',
  FavoriteSolid = 'star',
  Home = 'home',
  Info = 'info',
  Menu = 'menu',
  More = 'more_horiz',
  Notify = 'notifications',
  OpenInNew = 'open_in_new',
  OpenWith = 'open_with',
  Person = 'person',
  PersonOutline = 'person_outline',
  Refresh = 'refresh',
}
